cups:
  host: localhost
  port: 631
  printers:
    white: printerNameWhite
    pink: printerNamePink
    yellow: printerNameYellow

possy:
  redirect_to_file: true
  service:
    url: http://localhost:8080
    username: possy
    password: possy
server:
  port: 8081
