language: java
sudo: false
cache:
  directories:
  - $HOME/.m2
script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar
addons:
  sonarcloud:
    organization: "gerald24"
    token:
      secure: "jlQxCSSWxoq71tDxYXdyT7z+uwaYmF4/1+qmryKi7fQRGrUOhmMJ9aAm6SHAPAdxwUrJO2LGHzWLQbiCyVHqcvCpAt+BmAZS7uaCergCm2ovnhEsMwp+cRqfUc5wdy98tjF1jUM10NyNNgzk1m5aodvyUSGQWsHskmnbt2Bsnu9bNkvzcHHySunlOvrb/uQhwKSZA2khWHspqB22u/Rn4pSJFNhDbmh8J0r/PFVwguk1NkSywLXF8F9XFcKCeRSj0ojRvA/lT9OB6/2UEBTTggVVLAXDqwsRTZE4uE1gxyoUhNS5zraZo2a3qsoXtKZTBKOvttIpp3a9DRcuGwaWVBYrrm8XP00A4TX79p8nxUTxXDZFPKjEDdkFCyfQzVHbnNdxqxrVLMS2N2bn9Qm86wpoY+SDmXvr9h+YcwKvPjwae2mmTYNOU48mbXSF4LG9rEnZzolO2xFVT+2gyfPWt0ZG/FIeagnP7BV30yyoiFQVZMZjQezkLbocLDri+DxOxl634ftB2MsMJj/yjuEXWlehcpPwColjYbE2g39rVGxmfazlbTymk4YGeT2Hf/CAOCpFWHvrVVpt5NioZlzx+kb7kiI1+prJxc6ponrBKSoBHnj/e82rzTEFqBG1wO4fyluIx2utvunjbqOaawDen2b/pbhAAzG5oxbpZup+aQA="
deploy:
  provider: heroku
  api_key:
    secure: "U8kPR11d6gf8EMwGxu33TXgFEqLN3UVB6e3Df4TBtAYcuGchsUwfQ4CjEa5tZ13/Qe+K7sJiEG3roFDCW/c6zGaCTMRHz5anMt0MQYxW6vnQ2ld+4RY4z5Yy4yAqRpHNJh7XnAB9lFoadeYEBrRZZHewFfHoXQ+ccHE9/NNCk2UGuw9O339FAZ+Q5e8N3srU2IcCU2m1BsyV5WyclI0TW86bkDdhQZ/+uh7JDav+WntjK9GbGgKHLBVTfYckvkvpr/iFM14TYEt1VU/qa6kJ+FBHzRfhmlIpQ99fjPOc+asdPQNM91oPFygRjtnEAjv4TbCjdSUBImmzgEt+X6IoOeJo5UQoIpv7Z9L60VRgGGCHPBDJBdPaNRuEbtSFl85X9MX2+RVbkANSqGTCtLPuhz4eppv5DhlPEGVnFDNIRtKGhPGDttHombudc4SW2DTwV6maJbIsJManqsFdlJ66klLmFOWmf+rbMw9TD1Pd2iqiY7MLxEBZqnSpEkGRLgoJPlN+gOQsbqnC8G4I4bdvVRj70N1dAMoYekQZA68rdTQpkow1cHM9MCu/DiOPOnrlS5tKMeIfV6IpmZ+SBjsk57A1b0A2Yzjo5toqYN9Rw/zq3eFawCbDENjIyFFWWi6wZzyqqwlG0rQKH6XYRa2+WmB6L6/zSnBZSrngCWCom/4=" secure: "YOUR ENCRYPTED API KEY" secure: "YOUR ENCRYPTED API KEY"
  app: possy-service
