language: java
jdk: openjdk11
sudo: false

addons:
  sonarcloud:
    organization: "gerald24"
    token:
      secure: "jlQxCSSWxoq71tDxYXdyT7z+uwaYmF4/1+qmryKi7fQRGrUOhmMJ9aAm6SHAPAdxwUrJO2LGHzWLQbiCyVHqcvCpAt+BmAZS7uaCergCm2ovnhEsMwp+cRqfUc5wdy98tjF1jUM10NyNNgzk1m5aodvyUSGQWsHskmnbt2Bsnu9bNkvzcHHySunlOvrb/uQhwKSZA2khWHspqB22u/Rn4pSJFNhDbmh8J0r/PFVwguk1NkSywLXF8F9XFcKCeRSj0ojRvA/lT9OB6/2UEBTTggVVLAXDqwsRTZE4uE1gxyoUhNS5zraZo2a3qsoXtKZTBKOvttIpp3a9DRcuGwaWVBYrrm8XP00A4TX79p8nxUTxXDZFPKjEDdkFCyfQzVHbnNdxqxrVLMS2N2bn9Qm86wpoY+SDmXvr9h+YcwKvPjwae2mmTYNOU48mbXSF4LG9rEnZzolO2xFVT+2gyfPWt0ZG/FIeagnP7BV30yyoiFQVZMZjQezkLbocLDri+DxOxl634ftB2MsMJj/yjuEXWlehcpPwColjYbE2g39rVGxmfazlbTymk4YGeT2Hf/CAOCpFWHvrVVpt5NioZlzx+kb7kiI1+prJxc6ponrBKSoBHnj/e82rzTEFqBG1wO4fyluIx2utvunjbqOaawDen2b/pbhAAzG5oxbpZup+aQA="

cache:
  directories:
    - $HOME/.m2

stages:
  - compile-test
  - analyze
  - deploy-docker
  - deploy-heroku

# skip Travis default mvn step
install: true

jobs:
  include:
    - stage: compile-test
      if: fork = true # skip this step for internal use to avoid compiling twice, analyze step step will compile too
      script: mvn clean verify

    - stage: analyze
      if: fork = false
      script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar

    - stage: deploy-docker
      if: branch = master AND fork = false AND type = push
      env:
        - DOCKER_USERNAME=ajgassner
        # DOCKER_PASSWORD
        - secure: "4BrCzOE19dpcqLZ9Xowa6dWKn78dvQpY4ugHZdzxnEF8iru/n9LGP0PiKIgUcI0shv1F3ijmvzsDqoh8J0QlWU2AGaWC/R8MH58EhvKQSBDb/a9yLc3jKruW6IsAeOrAUmelm0nEew8kQJYuzaSKIPcBKlhXQG3duTjUR6t+KTDcPnVsd2sCDXfMShUlLwuPjBapXHPWCbSuI08Sdpct9hw/3Rldi8MygJoj6tUS10jKdVMw0LoohE7CEFYOSFUHyIWCKVL01ZxOyYQi9O5LZq+59hj5p9X6RyQerMNttA3sZuRs7g6f+I1oReY/wptWjHZ0RfhHFMcICVJnBn6Ji9+dZi0b2BRH650VSbNtzP/MKbtS/WGsB3+3xmlsqzB86L7VEf5oodFRRY0pPB7tYFcIUbBudW0l9XqntBBwUookKaCQItfYmovmAf4ItUDUh4QNyo+Tlibuc4FUJXHJx2FBoA2bP2EXum7Gr/9oxtES2hW60KNl20J7vnXaRJgnf6PfjMw2RIKO4oAeC4ep93QPQ6yMEUIVdOeeW2dbaqwB4Pa/hY6vjpSeISZlCWZRHybv4kb33PeaeQ/uFVNrsBTWu2kH5pDpxDmGLxZnIbtLSyTX7RlN4KeoCirblVDbyoGz9IUCKH5093P3hw6egiLnorejWU/19WLsuv9xksc="
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - sh -c 'cd service && mvn clean verify -DskipTests -Pprod'
        - docker build -t ${DOCKER_HUB_USERNAME}/possy-service:latest && docker push ${DOCKER_HUB_USERNAME}/possy-service:latest service
        - sh -c 'cd daemon && mvn clean verify -DskipTests'
        - docker build -t ${DOCKER_HUB_USERNAME}/possy-daemon:latest && docker push ${DOCKER_HUB_USERNAME}/possy-daemon:latest daemon

    - stage: deploy-heroku
      if: branch = master AND fork = false AND type = push
      env:
        # HEROKU_API_KEY
        secure: "2hRmhn9iVLFpXIAncBWqydrxOVq33DIeGqLAWeGcmfeG7m/lAnEOvOXFtIh7darJLomfsUdt5ujEocyTvJGeJfve0X9BxPc1z4FKTLLBoGjXk35wShJ98guq5YiVFyh+EVFUInsSVTroMWvBytrgql34WbX9y3dVVGGsrVA0jukcSrxPmliVOggDDXAbCMsZvtAhax8cO0A86FDu0sHFvs1EHEjoAn3biHkXB4LViZVORZucR0F8mg66KygwI0nzdaDpiJS0S8xzjKIgTYSyuALsobI4SLKk7XD6d9CpS7jUQ55aZzxuuDRKCpJecjVX4ZLmVjACrtSnTJvnj9Ed+S4EZS5WRWgNLZXafGCW932/mbycNp2nxkZbIJooZbGHeXHOt+JUrlgA9HXgTrYAsaKGHFTOkihLLvt7YqjABY5UH4zStgeZ8z93Yi2qHHsTf1R/ZVx6g9+446zJmNJ5j8LDIyYBMobxkAA6U6c0OyQnIaiQUHnw4TNYqY4x8AeGt24p7jDb3PGc5dBnQL4KMoC74KJdLIftjWm5jkk7bZEOh29uwyUg6GyPnHNawfWHpRqB5U8HEa2TrrpS7RRGgxJkVF5Alvz3Ux66XfRiTFq1ZsNbV39CZ2m4/KP1JNbL8LGRrrX1gGyUS49P2MEPKwQf1KLjm6VHy2wnbwVUq/w="
      script:
        - sh -c 'cd service && mvn clean heroku:deploy -DskipTests -Pprod'
        - sh -c 'cd daemon && mvn clean heroku:deploy -DskipTests'
