logging:
  level:
    org.atmosphere: warn

jira:
  url: https://jira.changeme.at/
  username: changeme
  password: changeme
  projects: PRJ1,PRJ2,PRJ3

possy:
  # important: change the key in production to any other complex value
  encryption-key: "cqWjqb5Fn3a8aVZwekCXEkjZW9gW77K6"

server:
  compression:
    enabled:  true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: possy
  devtools:
    restart:
      # Workaround for https://github.com/vaadin/flow/issues/5947
      additional-exclude: META-INF/VAADIN/config/**
  jackson:
    serialization:
      write_dates_as_timestamps: false
  security:
    user:
      name: possy
      password: possy

vaadin:
  whitelisted-packages: "net/g24/possy/service"
