logging:
  level:
    org.atmosphere: warn

jira:
  url: https://jira.changeme.at/
  username: changeme
  password: changeme
  jql:
    projects-recent-issues: "project=%s+AND+(created>=-1w+OR+updated>=-1w)+AND+(issuetype!=10100)+ORDER+BY+updated+DESC"
    fields:
      - issuetype
      - key
      - summary
      - customfield_10102 # story points
      - customfield_13017 # T-Shirt Size
      - customfield_10105 # epos reference
  mapping:
    content: summary
    weight: customfield_10102|customfield_13017.value # | = separator for fields, use first non null value
    tag: customfield_10105*.summary # * means pointer to another issue
    template-field: issuetype.id
    bug:
      - 1
      - 10200
      - 10800
      - 11105
    story:
      - 10101
      - 10201
      - 10500

possy:
  encryption-key: "cqWjqb5Fn3a8aVZwekCXEkjZW9gW77K6" # important: change the key in production to any other complex value
  remember-me-validity-seconds: 31104000 # one year
  admin:
    username: admin
    password: admin

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: shutdown, restart
  endpoint:
    health:
      show-details: when_authorized
      show-components: when_authorized
      roles: ACTUATOR

server:
  compression:
    enabled:  true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: possy
  devtools:
    restart:
      # Workaround for https://github.com/vaadin/flow/issues/5947
      additional-exclude: META-INF/VAADIN/config/**
  jackson:
    serialization:
      write_dates_as_timestamps: false
  security:
    user:
      name: possy
      password: possy

vaadin:
  whitelisted-packages: "net/g24/possy/service"
